---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocf-core
  name: ocf-core
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
    nodePort: 30800
  selector:
    app: ocf-core
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocf-core-ingress
  # annotations:
    # cert-manager.io/issuer: "letsencrypt-prod"
spec:
  # tls:
  # - hosts:
  #   - ocf-core.kube.home.davidassigbi.com
  #   secretName: kube-home-davidassigbi-com-tls
  rules:
  - host: ocf-core-lsd-sdv.duckdns.org
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ocf-core
              port:
                number: 80
